### ISSUE TITLE
Duplicate Jar entries

### ISSUE THREAD

**Issue by lucgirardin** [ascendtech/gwt-gradle#3]
When issuing the jar command, the resulting file contains all the classes and resources twice. This can easily be tested using the ascendtech/gwt-examples project:
```
./gradlew :todoMaterial:jar
jar tvf todoMaterial/build/libs/todoMaterial.jar | grep "ToDo\."
   687 Wed Jun 05 19:14:44 CEST 2019 us/ascendtech/ToDo.gwt.xml
   827 Wed Jun 05 19:15:12 CEST 2019 us/ascendtech/client/ToDo.class
   687 Wed Jun 05 19:14:44 CEST 2019 us/ascendtech/ToDo.gwt.xml
   827 Wed Jun 05 19:15:12 CEST 2019 us/ascendtech/client/ToDo.class
```
A workaround is to change the behavior of the jar task:
```
jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
```
but that isn't very good fix.

**Comment by mdavis95** [comment]
I am looking into this one.  Clearly I can add the DuplicatesStrategy.EXCLUDE internal to the plugin but I would like to see what is causing the duplication.

**Comment by mdavis95** [comment]
I really cant figure out where this is coming from in the Jar task.

**Comment by mdavis95** [comment]
@lucgirardin Do you have any ideas on this.  I would appreciate a pull request here as well.

**Comment by lucgirardin** [comment]
I wish I could submit a PR, but so far I only managed to understand the issue:

When the project is evaluated (when us.ascendtech.gwt.lib.GWTLibPlugin#apply is called), the values of the extension have not yet been evaluated. What you get are the default values of us.ascendtech.gwt.common.GWTExtension, even if you have orriden some of them in the project gwt {} block. This has for consequence that the code in GWTLibPlugin from line 92 to 105 will always be executed because includeGwtUser and forceRecompile are always true and there is no way to override their value at this stage.

This was my reason to introduce the forceRecompile flag, as I believe it is this block of code that is responsible for generating the duplicate Jar entries. For my usage, this block of code could just be removed (including the part for includeGwtUser), but I am sure it is there for a purpose. In principle, they should either go to a task or in a project.afterEvaluate {} block. I should maybe also comment that setting upToDateWhen to false isn't very elegant and has undesirable side effects.

Am I providing enough information so that you can make progress on this front?!?

**Comment by mdavis95** [comment]
Ok thanks, that helps some. I can dig some.

**Comment by mdavis95** [comment]
Gradle 6.0 warns about the duplicate files.  I will fix this in part of the upgrade to gradle 6.0.

**Comment by lucgirardin** [comment]
Very good! Let me know if you need help. I just submitted a PR with a bug fix that would be good to incorporate as part of the upgrade.

**Comment by mdavis95** [comment]
0.4.23 includes your bug fix and a exclude strategy options for jars and wars (all i had time to do)

**Comment by lucgirardin** [comment]
I gave it a quick try and everything seems to be compiling well now: many thanks :-)

**Comment by lupino3** [comment]
FYI, @pviotti in https://github.com/EduMIPS64/edumips64/pull/312 found out that the duplication is caused by the plugin adding the `processResources` task as a dependency for `compileJava`, which causes it to be executed twice.

**Comment by mdavis95** [comment]
Good to know. I will keep that in mind.
